version: '3.1'

services:

  db:
      image: mongo:latest
      container_name: database
      ports: 
        - "27017:27017"
 

  app:
      build: .
      container_name: fapi_app
      ports: 
        - "8081:8081"
   

  


